### ISSUE TITLE
bib-parameters has unexpected value and then cdr crashes

### ISSUE THREAD

**Issue by wosined** [jkitchin/org-ref#1001]
I had to change a line in `org-ref-export.el`.
Under your hard coded factor comment.
```lisp
	  (when (cdr (assq 'second-field-align bib-parameters))
	    (setq s1 (format
		      "<style>.csl-left-margin{float: left; padding-right: 0em;}
 .csl-right-inline{margin: 0 0 0 %dem;}</style>"
		      ;; I hard coded this factor of 0.6 from the oc-csl code.
		      0 ;;(* 0.6  (cdr (assq 'max-offset bib-parameters)))
              )))
```
The reason is that sometimes `bib-parameters` doesn't have a value for `max-offset`, but it does have the key. So `cdr` gives an error. Not sure why this happens.

I'm calling your function `org-ref-process-buffer` inside my custom export function. Is it relying on some hidden initialization? I don't thinks so, because I can call `org-ref-process-buffer` and it processes my buffer no problems. Maybe it's a csl problem. Anyways, I had to make this change.

Maybe this could be fixed with checking whether `assoq` returns a 2 element list and only then using `cdr`.

**Comment by jkitchin** [comment]
Thanks for reporting this. I think I have fixed it above. The issue is probably trying to do `(* 0.6 nil)`. I think the best thing is to add an or statement to make it 0 if it returns nil. your solution is not right for when there is a max-offset.

`org-ref-process-buffer` should usually be run in a processing hook on a copy of your buffer.

**Comment by wosined** [comment]
You are right, it was the `*` function that was signaling the error. It works now so I'm closing this.
