### ISSUE TITLE
only cited references show up in the bibliography

### ISSUE THREAD

**Issue by friedgreenrepos** [jkitchin/org-ref#1060]
i noticed only cited references show up in the bibliography section. is that the default behaviour?

**Comment by jkitchin** [comment]
that is the expected behavior. What were you expecting?

**Comment by friedgreenrepos** [comment]
i was expecting for all the entries to show up even if not cited in the thesis. i naively supposed that was the default behaviour... this is my first experience writing a thesis and i'm referring to the examples my professor gave me.  to "solve" I added `\nocite{*}` in my document and now everything is showing.
thanks for the quick reply anyway!

**Comment by jkitchin** [comment]
The \nocite{*} approach is indeed the way to get all the references. Some good reasons this is not the default is many people use one very large bibtex file to keep all references for different projects, and they are not all relevant to a single document, so the default is to only include items referenced unless you specify otherwise with \nocite{*}.

**Comment by friedgreenrepos** [comment]
makes perfect sense. i don't have a lot of experience nor a lot of bibliography items so i just presumed that was the default behaviour. anyways, thanks for the great work!!
