### ISSUE TITLE
Request for handling additional arguments

### ISSUE THREAD

**Issue by jag2** [jkitchin/org-ref#11]
I am still struggling with how org-ref handles additional arguments. When citing a page number, I would also like to see the author and year, and not just the page number. I know you can use org-toggle-link-display, but I would rather have something like [[citep:23Jones2013]], even if that would compromise the link functionality. With helm-bibtex it seems that these functions are just a few clicks away anyway.

**Comment by jkitchin** [comment]
This is not possible. It may get fixed in when org has a proper citation syntax, but for now it is not feasible in the link syntax. org-toggle-link display is the only way to see the citation and the pre/post text. Personally I think it is not useful to use pre/post text in org. You should just write "see page 23 in Ref. citenum:Jones2013" or (page 23 citet:Jones2013).

**Comment by jagrg** [comment]
Let me know if you think this is doable. Looking at `org-ref-format-citation-description`, I think we could add both the cite command and KEY to the link description and then ignore them when exporting. This way everything we need would be included in the link description (citation command, pre and postnote). Here is an example:

```elisp
(setq citation "citep-mao-2013-inter::see::12")
(setq citation "citep-mao-2013-inter::12")

(let ((results (split-string citation "::")))
  (if (= (length results) 2)
      (format "[%s]" (nth 1 results))
    (format "[%s][%s]" (nth 1 results) (nth 2 results))))
```

This is what I get in org-mode and latex respectively:

```
[[citep:mao-2013-inter][citep-mao-2013-inter::12]] 
=> \citep[12]{mao-2013-inter}

[[citep:mao-2013-inter][citep-mao-2013-inter::see::12]] 
=> \citep[see][12]{mao-2013-inter}
```

For some reason it doesn't always work on the first export. I'm not sure why.

**Comment by jkitchin** [comment]
Have you tried a recent orgref lately? The lite links with descriptions should now be expanded so you can see the whole thing now.

**Comment by jagrg** [comment]
Thanks. I had `org-ref-colorize-links` set to nil. It looks like it only expands when set to t. In any case, it's a lot better now, although I would still prefer this: `cite:key::text` over this: `[[cite:key][text]]`.

**Comment by jkitchin** [comment]
It does only expand when org-ref-colorize-links is set to t. I see the appeal of the notation, but I am hesitant to change the keys like that because so many things depend on acting on the key at point. I think it could be just modifying one function, but it would take more testing than I have time for.

**Comment by jkitchin** [comment]
I looked into an alternative idea, which is to totally change the overlay of the link to display something like you have described. I opted in the end to just open the link up to avoid confusion of the text looking like something else.
