### ISSUE TITLE
Title returns nil by 'doi-add-bibtex-entry'

### ISSUE THREAD

**Issue by aydemirfb** [jkitchin/org-ref#114]
Title returns nil for some DOIs.
DOI: 10.1023/a:1015522622034

**Comment by jkitchin** [comment]
Does that cause a problem? The issue is with dx.doi.org which doesn't have the title information. There isn't anything doi-utils can do about that. (i.e. in the json below, there is "title":null). You need to manually change the title if you know what it is. I guess that means Springer did not register the title yet, and some time in the future it will be updated. A similar issue happens with ASAP articles which have DOIs before they have volumes and page numbers. 

{"indexed":{"date-parts":[[2015,12,27]],"date-time":"2015-12-27T03:16:52Z","timestamp":1451186212636},"reference-count":0,"publisher":"Springer Science + Business Media","issue":"1","published-print":{"date-parts":[[2002]]},"DOI":"10.1023\/a:1015522622034","type":"journal-article","created":{"date-parts":[[2002,12,28]],"date-time":"2002-12-28T23:59:19Z","timestamp":1041119959000},"page":"1-26","source":"CrossRef","title":null,"prefix":"http:\/\/id.crossref.org\/prefix\/10.1007","volume":"34","author":[{"affiliation":[],"family":"Yavuz","given":"H."},{"affiliation":[],"family":"Bradshaw","given":"A."}],"member":"http:\/\/id.crossref.org\/member\/297","container-title":"Journal of Intelligent and Robotic Systems","deposited":{"date-parts":[[2012,12,28]],"date-time":"2012-12-28T13:31:48Z","timestamp":1356701508000},"score":1.0,"subtitle":[],"issued":{"date-parts":[[2002]]},"alternative-id":["383190"],"URL":"http:\/\/dx.doi.org\/10.1023\/a:1015522622034","ISSN":["0921-0296"],"subject":["Control and Systems Engineering","Mechanical Engineering","Electrical and Electronic Engineering","Industrial and Manufacturing Engineering","Software","Artificial Intelligence"]}

**Comment by aydemirfb** [comment]
No problem at all, it is a quick fix. I just wanted to report it. I'll just close the issue then.
