### ISSUE TITLE
Question: How do you manage keywords?

### ISSUE THREAD

**Issue by aydemirfb** [jkitchin/org-ref#123]
When I take notes on a paper, I usually assign tags/keywords (not talking about org-mode tags). For me a tag can be the topic of the paper, problem it solves, technique it uses,  benchmark it uses, or type of evaluation and so on. So a tag can be anything, and a paper may have multiple tags.  It is helpful to be able to see a list of papers that match a tag or multiple tags. My questions are:
   * Does org-ref support this type of functionality (something other than org-mode tags)?
   * What is your workflow if you also tag papers in your library?

**Comment by jkitchin** [comment]
If I am in my bibtex file, I have org-ref-bibtex-hydra/body bound to a convenient key (right now I use jj as a key-chord), and then I press k to add a keyword. That just calls org-ref-set-bibtex-keywords. I comma separate them.

From org-ref-helm-cite I can select entries and press f6 to add keywords to entries. There is actually a similar capability in helm-bibtex, but it is f11 I think (press tab to see the actions). 

I can also use org-ref-helm-cite to narrow to papers were a specific tag or combination. The candidates show the tags wrapped in :tag: so I can use that in the helm selection minibuffer.

In helm-bibtex I also added keywords as a column, so you can narrow by those too. It helps to use some kind of syntax on keywords, like :sometag: since helm just does text matches.

**Comment by aydemirfb** [comment]
very helpful, thanks!
