### ISSUE TITLE
different ref format depending on major mode

### ISSUE THREAD

**Issue by dl3br** [jkitchin/org-ref#130]
this is a feature request. when i'm writing latex, i would like to use org-ref. Specifically, org-ref-helm-insert-ref-link would be good. If i use org-ref-helm-ref-link, i get an org-file style citation in a latex buffer. If i use org-ref-helm-insert-cite-link it gives me a latex citation in the latex buffer.

What I'm suggesting is something similar to what is present in helm-bibtex, namelly  helm-bibtex-format-citation-functions:

(setq helm-bibtex-format-citation-functions
  '((org-mode      . helm-bibtex-format-citation-org-link-to-PDF)
    (latex-mode    . helm-bibtex-format-citation-cite)
    (markdown-mode . helm-bibtex-format-citation-pandoc-citeproc)
    (default       . helm-bibtex-format-citation-default)))

**Comment by jkitchin** [comment]
Can you do this with a hook? i.e. set the insert-link function when those modes are opened?

For citations this would be fine, as this is done via helm-bibtex, or some other completion tool like org-ref-helm-cite.

For labels and refs, it would take a lot of work because these rely on the ability to parse the org-file, and new code would have to be written to parse the various formats. I actually started this for latex here https://github.com/jkitchin/org-ref/blob/master/org-ref-latex.el, but it is pretty low priority work since I don't write in latex too often ;) and I realized how much work it would be to get org-ref behavior.
