### ISSUE TITLE
Byte compiling error when install org-ref from MELPA

### ISSUE THREAD

**Issue by et2010** [jkitchin/org-ref#133]
I got this error when install org-ref from MELPA

> org-ref-helm-cite.el:41:1:Error: Cannot open load file: no such file or directory, org-ref-citeproc

I tried to load org-ref-citeproc.el manually and redo the byte compile,  but I got this error:

> org-ref-helm-cite.el:13:34:Error: End of file during parsing

**Comment by jkitchin** [comment]
Thanks for reporting this. It shouldn't affect you as this file isn't used by default. I have pushed a fix that will hopefully fix that. It should also work fine if it is not byte-compiled.

**Comment by et2010** [comment]
Thank you. It works, no more error pops while compiling.

**Comment by et2010** [comment]
This issue is back, now these files cannot compile:
```
org-ref-helm-cite.el
org-ref-isbn.el
org-ref-latex.el
org-ref-bibtex.el
org-ref-core.el
org-ref.el
x2bib.el
```

**Comment by jkitchin** [comment]
hm.. I don't know how to fix this. the issue is related to the citeproc path, and the way that is added. it works fine except for the byte-compiling part. suggestions welcome!

**Comment by ericdanan** [comment]
I just tried installing `org-ref` from MELPA. For me only the three following files cannot compile:

```
org-ref-bibtex.el
org-ref-helm-cite.el
org-ref-core.el
```

The compilation error for the three file is the same:

```
Cannot open load file: no such file or directory, unsrt
```

For `org-ref-bibtex.el` the corresponding line is:

```
(require 'unsrt)
```

For `org-ref-helm-cite.el` and `org-ref-core.el`, the corresponding line is:

```
(require 'org-ref-bibtex)
```

So I'm not sure, but it seems that the problem would perhaps be solved if we find a way to make Emacs find the file `unsrt.el` when compiling `org-ref-bibtex.el`. Would moving the two `(add-to-list 'load-path ...)` statements from `org-ref-core.el` to `org-ref-bibtex.el` do? Or can the `(require 'unsrt)` statement in `org-ref-bibtex.el` be removed?

**Comment by jkitchin** [comment]
What we need to figure out is how to get the citeproc directory on the load-path during compile time. That would solve the issue.

I will try adding the load-path lines to org-ref-bibtex and see if it helps.

**Comment by jkitchin** [comment]
I think I have for now removed the unsrt require by putting it in the function that needs it. it might be a temporary fix I fix another way later. Some file from citeproc/csl needs to get required to set the citation format for the function. This is not a heavily used function yet though.

**Comment by ericdanan** [comment]
Before this fix I tried installing from `emacs -Q` and I got additional errors, with the exact same files as @et2010  (I should have done that from the beginning, sorry).

The unsrt error is gone after the fix. The other ones seem to come from the line

```
(require org-ref-completion-library)
```

in `org-ref-core.el`. The problem seems to be that the variable `org-ref-completion-library` is void when the file is compiled (I only saw this in `emacs -Q` because I bind this variable in my `init.el`).

The solution I found is to make the backends load `org-ref-core` instead of doing it the other way around. I tested it, all files compile and everything seems to work for me. But perhaps I'm overlooking some problems... I'll submit a PR so you can test it if you want.

**Comment by ericdanan** [comment]
Installing latest MELPA version (20160630.1742) in `emacs -Q`, all files are compiled (with warnings), except `org-ref-core.el`. The error is again due to `(require 'org-ref-completion-library)`, complaining that this variable is void. I don't think this prevents the package from working.

**Comment by jkitchin** [comment]
That is what I see too. Its hard to understand, since it is defined right above it ;)

**Comment by ericdanan** [comment]
I have perhaps found an explanation. From the elisp documentation and some googling, it seems that when a file is byte-compiled, the top-level `require` forms are evaluated (because they are supposed to load code that is needed for current file), but the compiled file itself is not loaded before being compiled. So if I understand correctly, the byte-compiler tries to evaluate `(require org-ref-completion-library)` in `org-ref-core.el` but the variable is void because its `defcustom` form has not been evaluated.

A simple solution seems to be to move `(require org-ref-completion-library)` to `org-ref.el`, after `(require 'org-ref-core)`. Now I'm afraid it is once again only working for me, but I'll still send you the PR.

**Comment by ericdanan** [comment]
With latest MELPA version (20160701.1007), no more compilation errors (juste some warnings) and all files are compiled, for me at least.

**Comment by et2010** [comment]
It works like a charm, thanks.
