### ISSUE TITLE
Show rendered latex equations in org-ref-helm-insert-ref-link

### ISSUE THREAD

**Issue by Titan-C** [jkitchin/org-ref#190]
I'm wondering if it is possible when using helm to insert a formula to show the latex rendered formula and not the latex code. For small documents I tend to remember well enough the labels, but as document size grows it becomes a harder task and I would like to scan over the formulas visually too because on big formula It is just intractable to read the source.

**Comment by jkitchin** [comment]
I don't know if you can do it in helm. It depends on whether it shows propertized strings.

There is some relevant work here: http://kitchingroup.cheme.cmu.edu/blog/2016/03/16/Getting-graphical-feedback-as-tooltips-in-Emacs/ and here http://kitchingroup.cheme.cmu.edu/blog/2015/10/09/Automatic-latex-image-toggling-when-cursor-is-on-a-fragment/ I think. There are a lot of corner cases to address though because of the number of ways a label can be attached to an equation, and all the other things that can be labeled. I can see why this is desirable, but it will be a while before I can get to trying it.
