### ISSUE TITLE
Pandoc-style citations

### ISSUE THREAD

**Issue by tarleb** [jkitchin/org-ref#228]
I am the maintainer of [Pandoc](http://pandoc.org)'s Org-mode reader and want to improve the reader's citation support.  *org-ref* seems to have evolved to the default referencing method, I am working towards enabling recognition of the *org-ref*-syntax with Pandoc.

Pandoc currently has its own citation syntax, designed by jgm for markdown and adapted to org-mode.  It would be great if *org-ref* and Pandoc could understand each other's format.

Pandoc's current syntax is

    [@citationKey]

for simple keys (LaTeX: `\cite{citationKey}` and

    [see @tarleb p. 34-35]

for more complex citations (`\citep[see][ p. 34-35]{tarleb}`).

There is also a outstanding issue (jgm/pandoc#1978) requesting support for `@citeKey` syntax, which is also supported in Pandoc's Markdown implementation.  It's nice and succinct syntax, yet I'm unsure if this should be implemented in the context of Org-mode; your opinions on this would be appreciated.

**Comment by jkitchin** [comment]
I don't see much hope for org-ref being aware of other syntax until the
new citation syntax in org-mode is in the master. I think it would be
similar to @citeKey. There was a lot of work in that direction, but I am
not sure it has led to a definitive solution yet. The need for a
citeproc has help things up a bit. I believe someone was looking into
the pandoc citeproc. I even started a citeproc project for org-ref, but
I am not working on it much now.

org-ref uses org-links right now because they are org-elements, which
lets it use a lot of the org-machinery to manipulate them, export them,
and make them functional, without a lot (besides requiring org-ref) of
intervention from users. None of this would work without that.

The simplest citation is just cite:key

The link syntax is pretty limited, but can handle this:

\citep[see][ p. 34-35]{tarleb}

like this:

[[citep:tarleb][see:: p. 34-35]]

This: [see @tarleb p. 34-35]
would be: [[cite:tarleb][see :: p. 34-35]] I think.

That is about as sophisticated as is possible with the link capability.

I am not sure I have answered your questions.


Albert Krewinkel writes:

> I am the maintainer of [Pandoc](http://pandoc.org)'s Org-mode reader and want to improve the reader's citation support.  *org-ref* seems to have evolved to the default referencing method, I am working towards enabling recognition of the *org-ref*-syntax with Pandoc.
>
> Pandoc currently has its own citation syntax, designed by jgm for markdown and adapted to org-mode.  It would be great if *org-ref* and Pandoc could understand each other's format.
>
> Pandoc's current syntax is
>
>     [@citationKey]
>
> for simple keys (LaTeX: `\cite{citationKey}` and
>
>     [see @tarleb p. 34-35]
>
> for more complex citations (`\citep[see][ p. 34-35]{tarleb}`).
>
> There is also a outstanding issue (jgm/pandoc#1978) requesting support for `@citeKey` syntax, which is also supported in Pandoc's Markdown implementation.  It's nice and succinct syntax, yet I'm unsure if this should be implemented in the context of Org-mode; your opinions on this would be appreciated.
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/228


--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by tarleb** [comment]
Thanks for the feedback.  I guess you are right about wanting to wait till the official org-mode syntax finalizes.  I'll close this issue for now.

Pandoc support of org-ref syntax won't be complete for now, only `cite:`, `citep`, `citet`, and `citeyear` are supported (#2950). I will add more natbib commands later on.

Thanks again and happy hacking.

**Comment by bdarcus** [comment]
Do you know the status of the org-mode official work? It seems, almost four years later, the citation branch is still WIP?

They really need an issue tracker.

**Comment by jkitchin** [comment]
I believe it is still wip. I haven't heard anything about it moving to master yet.
