### ISSUE TITLE
Using default bibliography in export if nothing else is specified.

### ISSUE THREAD

**Issue by cpaulik** [jkitchin/org-ref#264]
org-ref falls back on `org-ref-default-bibliography` when no other bibliography is specified in a file. Could the same behavior be implemented during export? This would make the behavior consistent. At the moment everything seems to work in the org-file but the export breaks.

I guess this would mean introducing a variable for a default citation style since it is also needed for successful exporting.

**Comment by jkitchin** [comment]
This isn't something that can be done in org-ref I think. I have done it
in the past, but it requires a new exporter, or some export hooks that
modify the tex output, or a temporary copy of the org file before
export. 

You can see how it was implemented here:

https://github.com/jkitchin/jmax/blob/master/ox-manuscript.el#L537

I do not recall what we did about the style, but probably at one point
it was probably just unsrt.

It never worked as well as I thought it should, because you probably should
check if a bibliography is even needed, and there aren't many options
other than to put a bibliography link at the end of the document. 

A place you might put this is in `org-export-before-processing-hook',
though, as a function that just checks if you have an org cite link, and
not the bibliography links, and if so, insert them at the end.

Christoph Paulik writes:

> org-ref falls back on `org-ref-default-bibliography` when no other bibliography is specified in a file. Could the same behavior be implemented during export? This would make the behavior consistent. At the moment everything seems to work in the org-file but the export breaks.
>
> I guess this would mean introducing a variable for a default citation style since it is also needed for successful exporting.
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/264


-- 
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jkitchin** [comment]
This might do what you want. You need dash (which is already required in org-ref). You could add a variable for the default style too.

```
(defun org-ref-include-default-bibliography (backend)
  "Add bibliographystyle and bibliography links on export if they are needed."
  (cond
   ((eq backend 'latex)
    (let* ((links (org-element-map (org-element-parse-buffer) 'link #'identity))
	   (cites (-filter (lambda (link)
			     (member (org-element-property :type link) org-ref-cite-types))
			   links))
	   (style (-filter (lambda (link)
			     (string= (org-element-property :type link) "bibliographystyle"))
			   links))
	   (bibliography (-filter (lambda (link)
				    (string= (org-element-property :type link) "bibliography"))
				  links)))
      (when cites
	(unless style
	  (goto-char (point-max))
	  (insert "\nbibliographystyle:unsrt"))
	(unless bibliography
	  (goto-char (point-max))
	  (insert (format
		   "\nbibliography:%s"
		   (mapconcat (lambda (x)
				(file-relative-name x (file-name-directory (buffer-file-name))))
			      org-ref-default-bibliography ",")))))))))


(add-hook 'org-export-before-processing-hook #'org-ref-include-default-bibliography)
```

**Comment by cpaulik** [comment]
Wow thanks. That works well in my very limited (one) test.
