### ISSUE TITLE
open pdf for mendeley

### ISSUE THREAD

**Issue by autosquid** [jkitchin/org-ref#265]
The code provided for find (and get path for ) pdf in manual does not seem work well for mendeley bib with '-' as delimiter due to  `bibtex-completion-find-pdf`.  (see https://github.com/tmalsburg/helm-bibtex/issues/105)

So maybe it is necessary to provide the old way with 

`(pdf-file (funcall org-ref-get-pdf-filename-function key))`

I am not sure about this, the best solution seems like further  improvement of `bibtex-completion-find-pdf` though the author said " Anyway, I'm not going to work on this because I don't use Mendeley".

**Comment by jagrg** [comment]
I think he would accept a PR for this kind of thing. In any case, maybe we could add a note about `org-ref-get-mendeley-filename` in the manual. WDYT?

**Comment by autosquid** [comment]
@jagrg  y, I agree, and that is what I intended to say. Maybe I'll submit a P.R. when I am free.

**Comment by jagrg** [comment]
I've added a note about `org-ref-get-mendeley-filename`. It may be useful in the meantime.

**Comment by ajsteven130** [comment]
Hello,

I had a similar problem where `org-ref-get-mendeley-filename` did not work for my files. I wrote some functions that worked most of the time, including for files that contain '-' characters. It does not work for filenames that contain special characters.

The gist for it is here: https://gist.github.com/ajsteven130/3ea989a342fd706a1703d6fa4e970b5d

I never contributed them back to the repository because the implementation is hacky:

1.  the fact that I am using drive `c:/` is hard coded into the filename processing. This would be easy to fix
2. it only works if the first filename in the 'file' field is the pdf file. It does not cycle through the strings looking for a pdf. This should be easy to fix too.
3.  the error handling only sort-of works. 

For a personal solution, it was good enough. If we can clean up and test the code, perhaps we could eventually submit a pull request, but we need to find people who use successfully use the mendeley implimentation as it currently exists because I would hate to break things for them.

Another option is to try to migrate to the [bibtexkey].pdf format. If you have just a few files, you can use the new function `org-ref-bibtex-assoc-pdf-with-entry` which, when you are in a bibtex entry, will prompt you for a pdf file, then rename that file to [bibtexkey].pdf and copy it to  `org-ref-pdf-directory`. See more at #272

If you have too many files for that option, I have a python script that will scrape through your bibtex file and recopy the pdfs to a directory of your choice using the naming convention [bibtexkey].pdf. The script works for any file that does not contain special characters. If you are interested, I can upload the script to github. It is very unfortunate that Mendeley does not give you the option to name pdfs according to bibtex key..
