### ISSUE TITLE
Feature request: make org-ref cites "Org Descriptive Links" 

### ISSUE THREAD

**Issue by notuntoward** [jkitchin/org-ref#345]
org-ref is so impressive that I plan to put it in my workflow even though one thing about it is really bugging me:  The vast majority of my org docs are notes that are never turned into beautiful latex/pdf documents.  Since this is where I spend the most of my time, I like org bibtex refs -- as I see them in emacs org mode -- to be as readable as possible.  Ideally, the org file appearance should look like the combination of:

    C-c l           (org-store-link)

in a bibtex file, followed by

    C-c C-l         org-insert-link

in an org file.  Since I have the org customization

    "Org Descriptive Links" 

turned on, these bibtex cites look almost like what I'd see in a paper.  The org-insert-link interface is also good because it lets me type a more meaningful link name: a month after I write an org file, a bibtex link like:

    **cite:Pya15shapeCnstrAddMdl**

might mean nothing to me but this might:

    **Pya & Wood 2015: Shape Contrained Splines, no endpoint**

So, my feature request is to give org-ref the ability to make descriptive links.  Can this be done?

**Comment by jkitchin** [comment]
See 3b31021. It appears to work with C-c l on a bibtex entry, and then C-c C-l in an org-file.

org-ref makes cite links with descriptions unfolded, since the main use for descriptions is to add pre/post text to the export. 

In your workflow, I would use vanilla cite links, and add as text around it the description that makes it relevant. that is what the tooltips are for, to remind you the details of the citation.

**Comment by notuntoward** [comment]
Thanks for the really quick work. I hate to say it, but I was hoping for was really something that looks like the original bibtex links: [Pya & Wood 2015].

The new link type is longer and, in my opinion, redundant (both key and short description) and distracting (with the noisy [[*]]*[[]]).  And it contains a string that's not informative when you're just reading, not programming (cite:).  

Or am I missing something? You mentioned that I should use vanilla cite links.  Did you mean this style:

cite:Pya15shapeCnstrAddMdl

or did you mean there was a customization that makes the new links look like [Pya & Wood 2016]?

**Comment by jkitchin** [comment]
What you want is not possible. The description with cite links is for [pre text::post text] in the export, and they are unfolded so you can see the key and pre/post text, because otherwise it is hard to see what is cited. There isn't a way to have it both ways right now. 

If you want it to fold, you can add this to your init files if you use org-9. If not, you are out of luck, I don't think you can undo the folding in org-8.

(org-link-set-parameters "cite" :display nil) 

Note, these will not export the way you expect (or want I assume) though.

For instance:

[[cite:abild-pedersen-2007-scalin][Abild-Pedersen et al. 2007: Scaling Properties Adsorption]] 

exports as 

\cite[Abild-Pedersen et al. 2007: Scaling Properties Adsorption]{abild-pedersen-2007-scalin} 

because the description is considered pretext. This would limit the utility of your notes (in my opinion) as you wouldn't be able to just copy them elsewhere and get the right behavior.

I did mean just use cite:Pya15shapeCnstrAddMdl. if you mouse over this, you get a tooltip of the formatted reference with authors, title, journal etc., and when the cursor is in it, you get a minibuffer message of the same thing. Also, you can put the description in plain text right after or before it. I.e. you would never have something like **cite:Pya15shapeCnstrAddMdl** without some context around it that tells you what it is about, and the tooltips/minibuffer messages can provide additional context on demand. I guess this is different than what you are used to.

**Comment by notuntoward** [comment]
Thanks very much for the answer.  I have to admit that I don't understand
the pretext problem.  I nilled out :display, the cites{} in the .tex file
look good, as do the exported pdf and html files.  Where should I look for
this problem?

In other news, I just watched your excellent video on the new Org 9 links.
It gave me some ideas!

**Comment by notuntoward** [comment]
Sorry, *now* I see the export problem.  Is whatever code messes up the prefix outside of org_ref or org_mode?

**Comment by jkitchin** [comment]
It is a feature of orgref. You can change the export if you want locally. I
don't think that feature will change in orgref though. It is the only way
to get pre/post text.

**Comment by notuntoward** [comment]
Too bad!  I really want to keep orgref around because it has many useful features.  Luckily, export to html -- by far my most common export -- still works perfectly, regardless of how I set cite: display.  So I guess I don't mind per-file modifications for my occasional latex exports.  Can I actually use some org-mode #+* directive to set :display to 'full' or did you have another suggestion?

**Comment by jkitchin** [comment]
Display is only how it looks in orgmode. It has no effect on export. You
can independent set the :export function to get what you want.

**Comment by jkitchin** [comment]
html export would work fine, the pre/post text is only used in the latex exporter.

You could use local file variables that evaluate code when you open the file, or directory local variables for that too.

**Comment by Ypot** [comment]
Just a doubt. Could it be modified (or chosen) the cite format? 

For example, instead of this link:
 cite:abild-pedersen-2007-scalin

Obtain directly a link like this: 
cite:Abild_Pedersen-2007-Scaling_Properties_Adsorption

**Comment by jkitchin** [comment]
I am not sure why you would want to get that link. That link should contain the bibtex key of the entry you are citing, so if the key is abild-pedersen-2007-scalin, it is an error to use Abild_Pedersen-2007-Scaling_Properties_Adsorption.

If you mean, can org-ref generate that key for an entry then I am not sure. See the function `bibtex-generate-autokey`. You may be able to adapt something to get that key format.

**Comment by Ypot** [comment]
Hi

Yes, I was referring to a customization of the keys format. But as I can deduce from your answer it is very "unorthodox" I'll forget about it. 

Thanks.

**Comment by Ypot** [comment]
Just a newbie guess: could be easily solved the OP problem just by using Zotero to export library.bib with the keys in an explicit format, ie.
[auth99_1:capitalize][auth99_2:capitalize]-[year]:[title:capitalize]

I don't know if this could give some problems, I hope not, I too find it useful if reading is done on orgmode or orgzly, more than in paper or pdf.

**Comment by jkitchin** [comment]
maybe, in theory that should be fine. I avoid underscores whenever I can though, they almost always cause me some LaTeX problem, and I don't like to type them. The problems are usually in filenames, but I generally avoid them.

**Comment by notuntoward** [comment]
I've just come back to this, and I'm finding that ` C-c l` on a bibtex entry no longer gives me the option of storing a cite link.  The only storing function option is `org-bibtex-store-link`.

Is some additional configuration now needed beyond:

```
(use-package org-ref)
(define-key global-map "\C-cl" 'org-store-link)
``` 
?

**Comment by jkitchin** [comment]
hm. There is still a function called `org-ref-bibtex-store-link` that you can run manually to store a link. That is also stored as the store function on a link.

I think for some reason it shows you that option as default, if you delete that function, you should see the other options, including one for org-ref.

**Comment by notuntoward** [comment]
Oh yeah, you're right.  If I delete `org-bibtex-store-link` from the minibuffer, _then_ I can see `org-ref-bibtex-store-link`  Thanks!

Now, to somehow change the sorting, so `org-ref-bibtex-store-link` is on top and visible...

**Comment by jkitchin** [comment]
This is very lightly tested:


```
(let ((lnk (assoc "bibtex" org-link-parameters)))
  (setq org-link-parameters (delq lnk org-link-parameters))
  (push lnk org-link-parameters)) 
```

It should remove the bibtex link and put it at the front. The problem was this link was last, and is what showed up. Now, the org-ref function is last, and instead of seeing org-bibtex-store-link in the completion when you store the link you will see the org-ref function. IF you never use the org-bibtex-store-link, you might just remove it from the `org-link-parameters`.

**Comment by notuntoward** [comment]
Thanks for the very quick fix.  In your mind, is this something that should be fixed in org-mode?  It seems as if multiple link options aren't properly displayed.  I'll submit an org-mode bug upon your say-so.

**Comment by jkitchin** [comment]
I am not sure, the issue is that a default is offered that masks the other options. It would be my preference that it show all the options so you can choose one. That is probably something that should/could be fixed in org-mode. Or, all the links should be saved, and you choose what you want when you insert it. I don't use links this way much anymore, so it isn't critical to me.
