### ISSUE TITLE
org-ref doesn't do latex bibtex latex latex

### ISSUE THREAD

**Issue by notuntoward** [jkitchin/org-ref#346]
When I do M-x org-export-dispatch on test.org (attached), everything runs and I get a pdf -- but one with question marks instead of reference numbers.   The *ORG PDF Latex Output Buffer* says that the citations are undefined.  

Leftover in the directory is the file test.tex, and If I do usual incantation:

latex test
bibtex test
latex test
latex test
dvipdfm test

then I get a pdf with perfect citations.  

What setup should I do to get this sequence of calls?  Or is there a better way?

[test.zip](https://github.com/jkitchin/org-ref/files/612154/test.zip)
[test.pdf](https://github.com/jkitchin/org-ref/files/612161/test.pdf)
[OrgPDFLatexOutputBuffer.txt](https://github.com/jkitchin/org-ref/files/612162/OrgPDFLatexOutputBuffer.txt)

**Comment by lixinchin** [comment]
I think this is more an issue with org-mode itself rather than org-ref.

The conversion from a .tex file to pdf is controlled by the variable `org-latex-pdf-process`, which defaults to `'("%latex -interaction nonstopmode -output-directory %o %f"
  "%latex-interaction nonstopmode -output-directory %o %f"
  "%latex -interaction nonstopmode -output-directory %o %f")`
where `%latex` gets replaced by the contents of `org-latex-compiler` (default `pdflatex`). That is, by default, org-mode converts latex to pdf by just blindly running `pdflatex` three times and hoping for the best.

If you have `latexmk` installed (it's included in TeXLive, not sure which LaTeX distribution you have installed), then you can do
`(setq org-latex-pdf-process '("latexmk -pdflatex='%latex -shell-escape -interaction nonstopmode' -pdf -output-directory=%o -f %f"))` in you emacs init file, and let `latexmk` take care of running latex and bibtex the correct number of times.

**Comment by notuntoward** [comment]
latexmk solved the problem.  Thanks very much!

**Comment by notuntoward** [comment]
To make this work on a Windows 7 machine, I had to remove a few flags.  This worked:

    (setq org-latex-pdf-process '("latexmk -pdf -output-directory=%o -f %f"))

On a Windows 10 machine with what I think is an identical install of emacs and TexLive, the full setq worked fine.  But on Windows 7, latexmk.exe was calling latexmk.pl using a copy of its own arguments, but latexmk.pl considered:

    -pdflatex='%latex -shell-escape -interaction nonstopmode' 

to be illegal arguments.  I have no idea why there is a difference.

**Comment by tlkahn** [comment]
In addition, I have to add the following to the bottom of my org document to make everything work:
```

# <<References>>
bibliographystyle:unsrt
bibliography:/Users/MyUserName/Dropbox/bibliography/references.bib
```
