### ISSUE TITLE
Getting a "No PDF(s) found." when trying to add a reference

### ISSUE THREAD

**Issue by jackjackk** [jkitchin/org-ref#355]

**Comment by jkitchin** [comment]
Perhaps there is no PDF to be found. You will have to provide more information about what you are trying to do to determine if this is a bug.

**Comment by Cumol** [comment]
I have a similar issue and I think that it is connected to what @jackjackk is experiencing.

This started sometime in the last 3 weeks (no specific date, sorry). I am on Org 9 right now.

When I want to insert a citation, I get the Helm buffer to search for an article. The moment I press Enter to pick the article, Emacs opens the PDF (in Skim) instead of adding the citation. When I do that with an article that does not have an attached PDF, I get the "No PDF(s) found." error.

Any idea what could cause it? What additional information is needed?

**Comment by larstvei** [comment]
I have the exact same problem as @Cumol  describes.

Org-mode version 8.3.4
org-ref: Version 1.0.0 (git-commit fb5ae52c07dd64d71ea4043e34b299f747418d68)

**Comment by jkitchin** [comment]
I guess you might need to try updating helm-bibtex. That worked for one of my students.

**Comment by larstvei** [comment]
That worked for me as well @jkitchin!
