### ISSUE TITLE
Related to Issue #297: Managing multiple projects, each with own notes.org files and bibtex-pdfs folders

### ISSUE THREAD

**Issue by NLisa** [jkitchin/org-ref#368]
When using [org-ref](https://github.com/jkitchin/org-ref/), the `bibliography:ref.bib` directive in the `notes.org` file can be used to direct it to the corresponding `ref.bib` bibliography. Is there a similar such directive or approach to enable the `ref.bib` file to "discover" its corresponding `notes.org` file and `bibtex-pdfs\` folder?

Now, as per the documentation one can set the following within their `init.el`, or `emacs-init.org` file:

    (setq org-ref-bibliography-notes "~/Dropbox/bibliography/notes.org"
          org-ref-default-bibliography '("~/Dropbox/bibliography/references.bib")
          org-ref-pdf-directory "~/Dropbox/bibliography/bibtex-pdfs/")

However, in the case of multiple projects, each with their own `notes.org` and `ref.bib` files, and `bibtex-pdfs\` directories, how can one specify and associate a `ref.bib` file with a specific `notes.org` file and `bibtex-pdfs` folder?

Specifically when working on an article within a project, it's pretty neat to click on a reference that's been inserted with `C-c ]`, and then "Add Notes" to that particular reference `3 RET`.

Without the above snippet in my `init.el`, I get the following error:
`org-ref-open-bibtex-notes: Org-ref-bib-bibliography-notes is not set to anything`

This error persists even after setting up file local variables:

    * File Local Variables
    # Local Variables:
    # org-ref-bibliography-notes: "~/Dropbox/bibliography/notes.org"
    # org-ref-pdf-directory: "~/Dropbox/bibliography/bibtex-pdfs/"
    # End:

or:

    # -*- org-ref-bibliography-notes: "~/Dropbox/bibliography/notes.org"; -*-
    # -*- org-ref-pdf-directory: "~/Dropbox/bibliography/bibtex-pdfs/"; -*-

Thanks,
NLisa

**Comment by jkitchin** [comment]
I think you need to put the local variables in two places, which is the org file and the bib file. The issue is that the notes functions are called while the bibtex buffer is active, so the local variables in the org file do not affect them. 

In my org file I put something like

`* File Local Variables
# Local Variables:
# org-ref-bibliography-notes: "/Users/jkitchin/tmp/org-ref-issue-368/notes.org"
# org-ref-default-bibliography: ("/Users/jkitchin/tmp/org-ref-issue-368/test.bib")
# bibtex-completion-notes-path: "/Users/jkitchin/tmp/org-ref-issue-368/notes/"
# org-ref-pdf-directory: "/Users/jkitchin/tmp/org-ref-issue-368/bibtex-pdfs/"
# End:`

In the bib file I put 

`# -*- org-ref-bibliography-notes: "/Users/jkitchin/tmp/org-ref-issue-368/notes.org"; bibtex-completion-notes-path: "/Users/jkitchin/tmp/org-ref-issue-368/notes/"; org-ref-pdf-directory: "/Users/jkitchin/tmp/org-ref-issue-368/bibtex-pdfs/"; -*-
`

at the top in one line. That seems to be the only way to get the right thing to happen since the doi utils append to the end of the file and don't look for local variables.

There might still be a notes issue I am looking into, but this is what should be required to work with project specific variables I think.

**Comment by jkitchin** [comment]
It doesn't look possible to make directory specific notes right now. With this, it looks possible to use a directory specific default bibtex file. However, 

```

(setq enable-local-variables t)


* File Local Variables
# Local Variables:
# org-ref-bibliography-notes: "/Users/jkitchin/tmp/org-ref-issue-368/notes.org"
# org-ref-default-bibliography: ("/Users/jkitchin/tmp/org-ref-issue-368/test.bib")
# bibtex-completion-notes-path: "/Users/jkitchin/tmp/org-ref-issue-368/notes/"
# org-ref-pdf-directory: "/Users/jkitchin/tmp/org-ref-issue-368/bibtex-pdfs/"
# End:

```
