### ISSUE TITLE
Allow to create cross-references/internal links to <<targets>> (feature request)

### ISSUE THREAD

**Issue by thblt** [jkitchin/org-ref#385]
Unless I've missed something, creating an internal reference with org-ref is limited to section headings with `CUSTOM_ID` (and other similar entities)  This is good for research papers and highly structured contents, but not so good for note taking.  Would it be possible to add support for references to in-text `<<targets>>` to org-ref?

Apologies if it exists and I missed it :-/

Thanks,
Th

**Comment by jkitchin** [comment]
That wouldn't make sense for LaTeX exports. I think you can only reference things that are numbered. 
In org you can do that kind of link with this syntax:

`A test with <<radio>> target. Now can you can reference that [[radio]].`

Even that doesn't export with links in LaTeX actually, the <<radio>> doesn't appear, and there is no link for the ref.

Is what you want just completion for the radio targets?

**Comment by thblt** [comment]
Thanks for your answer,

 1. Re LaTex

    I agree it would make *limited* sense for LaTeX export, but it could still be useful to reference the page a paragraph is on, or a specific footnote.    IIRC, LaTeX has support for randomly-placed labels, and would just refer to them as a page number (or page/note number).   I believe I already used this kind of labels to reference a piece of information which doesn't have its own (sub(sub))section.

    Using only standard org, LaTeX export seems to work:

    ``` org-mode
    Lorem ipsum[fn:1].

    See note [[fn]]

    * Footnotes

    [fn:1] A footnote <<fn>>
    ```
  
    exports to

    ``` latex
    \begin{document}

    \tableofcontents

    Lorem ipsum\footnote{A footnote \label{org42819b4}}.

    See note \ref{org42819b4}
    \end{document}
    ```

 2. Re the feature request

     Yes, what I'd really like to have is completion for these radio targets (didn't know the name, so thanks!).  Something like a generalized version of `org-ref-helm-insert-ref-link` and `org-ref-helm-insert-label-link` would be really useful for me.  

    The use-case for that is note taking, because when you know what your structure is going to be, `CUSTOM_ID`s are perfect; but when you don't, `<<radio targets>>` are amazing.  I'm in the “humanities”, and I often have to collect a fair amount of data from different sources on a single topic.  I usually have a huge org file for each topic, and gather data by using them as a personal wiki, with a quickly-moving structure and a lot of hyperlinking.  I'd rather not use `CUSTOM_ID`s because a) they're cumbersome, even with yasnippet, and b)  I sometimes have a single paragraph associated with two, three or even more radio targets, because it discusses very briefly multiple topics.  I'd rather not split it in multiple sections half a sentence in length, but sometimes I reorganize things, or some parts grow, and I can just move the targets along with the part they refer to.   

    The problem, of course, is I often have a faint idea of the kind of words that make the radio target I'm looking for, but not these exact words or their ordering.  That's where completion would really be great too have.

**Comment by jkitchin** [comment]
Your footnote example works because they are numbered. <<fn>> does export to \label{fn},  and [[fn]] exports to \ref{fn}, and it works in your case because the label is in a numbered item. If you put it in a paragraph though, LaTeX will not be able to make a link to it.

It is true that you can use a \pageref{fn}, and you will get a page number in LaTeX.  That is the only ref type that makes sense for radio targets that are not in numbered items I think though.

I don't mind adding radio targets to completion for these, although I have a little concern it could be confusing since they might not always work as expected if you don't know that pageref is all that will do what you want for targets in non-numbered locations. Also pageref doesn't make sense if you just use org or html export, which don't really have page numbers.

I could add it to the list of labels you can make a ref to, and make ref links work with them, and leave it up to users to make sure they use the right kind of ref if they do latex export I guess. What do you think?

**Comment by thblt** [comment]
> I could add it to the list of labels you can make a ref to, and make ref links work with them, and leave it up to users to make sure they use the right kind of ref if they do latex export I guess. What do you think?

Sounds perfect to me.  If you're worried about usability, maybe adding a customize option to enable the feature could help?   Something like `(defcustom org-ref-include-radio-targets-in-completion nil ...)`?  

Thanks,
Th.

**Comment by jkitchin** [comment]
I went ahead and added some support for this. The radio targets should now be listed as labels you can make a ref to. I guess this won't be too confusing in the grand scheme of things. if it is, we could consider a feature to turn it off.

For inserting labels, they should also be listed, and in the helm insert function if you type C-u before pressing enter, it should insert a radio target instead of a label link (I think both are fine, but maybe you like the way radio links look better?) 

give it a try and let me know what you think.

**Comment by thblt** [comment]
It seems to work perfectly well, thank you so much!  I'm currently working on one of these huge org-mode “wiki” files, I still have a few hours of work to give it an extensive try.  I'll report back to you this evening (GMT+1).  Thanks again!

**Comment by thblt** [comment]
After a short afternoon of testing, it seems perfect.  Thanks a lot again, and please tell me if you need more/more specific testing.

**Comment by jkitchin** [comment]
Sounds great, thanks! I think we can leave it at this for now. Thanks for confirming it works for you. Best wishes,
