### ISSUE TITLE
doi-add-bibtex-entry prints 'nil' in bibtex entry

### ISSUE THREAD

**Issue by jabranham** [jkitchin/org-ref#415]
For journals that publish articles online before they're printed, oftentimes some of the fields don't have values yet (issue number, pages, etc). Currently `doi-add-bibtex-entry` puts `nil` in those fields, which is probably a holdover from how elisp handles missing values. It seems better to me to omit those fields or leave them blank, though.

I'm not sure if this would be better solved in modifying the behavior of `doi-add-bibtex-entry` or adding a function to `org-ref-clean-bibtex-entry-hook`. 

Here is a doi that currently returns `nil` for volume, number, and pages for me: 10.1080/17457289.2017.1300157

**Comment by jkitchin** [comment]
I am calling that a "feature". It would be easy to get rid of them, but they serve a purpose in a way. When there is a nil in a field (which how elisp handles none values), then you can can clean the entry and the field stays. For new articles that don't have pages or volumes (but will later) I find this helpful because you can later run ‘doi-utils-update-field’ to get those values. There is also doi-utils-update-bibtex-entry-from-doi, but it overwrites any changes to fields you have made so I rarely use it.

I agree it is annoying to have residual nil in the number for journals that don't support it. I manually delete these fields eventually. If you wanted to put a function in to remove those, I would put it in org-ref-clean-bibtex-entry-hook. For me it would need some logic like, when on an article and there is a volume, and not a number, delete the number.

**Comment by jabranham** [comment]
That makes sense, thanks. I'll probably add that to the cleaning hook, then. The current behavior makes it so that if I forget to manually remove the nil's then they get printed in the pdf bibliography, which isn't right.

Once I do that, would you like it as a PR or should I keep it to myself?

**Comment by jkitchin** [comment]
That happens to me too, and I usually do the manual cleaning after reading the bibliography ;)

I would be happy to take a pull request. It should just be for the function. I pushed a function that will remove nil in the case where you a volume and pages, but no number in an article. Are there other scenarios where it definitely makes sense to remove them?
