### ISSUE TITLE
Not able to open notes.org file for citation

### ISSUE THREAD

**Issue by Cumol** [jkitchin/org-ref#486]
I am trying to add notes to a citation I have in a file through the menu that pops up when clicking on a citation. However, I keep getting this error:

`Org-ref-bib-bibliography-notes is not set to anything`

My setup in the user.el file looks like this:

```
(setq reftex-default-bibliography '("~/ownCloud/phd/papers/bibliography.bib"))
;; *** Org-ref
(setq Org-ref-bibliography-notes "~/ownCloud/phd/papers/notes.org"
      org-ref-default-bibliography '("~/ownCloud/phd/papers/bibliography.bib")
      org-ref-pdf-directory "~/ownCloud/phd/papers/")
;; *** helm-bibtex setup
(setq bibtex-completion-bibliography
      '("~/ownCloud/phd/papers/bibliography.bib"))
(setq bibtex-completion-library-path '("~/ownCloud/phd/papers/"))
(setq bibtex-completion-notes-path "~/ownCloud/phd/papers/notes.org")
```
I also created the notes.org file thinking that org-ref is not able to create the file.

I have a feeling I am missing something very basic. Any idea what is happening?

A side note, invoking helm-bibtex is not detecting my bibliography file (not showing any entries). Maybe it is a hint

**Comment by jkitchin** [comment]
Off the top of my head I guess that Org-ref-bibliography-notes should be org-ref-bibliography-notes (not capitalized). I don't see anything wrong in the other variables that would suggest why helm-bibtex wouldn't show entries. Have you tried running M-x bibtex-validate in the bib file to make sure it is syntactically correct?

**Comment by Ypot** [comment]
Hi
It seems I have the same problem. I can't create notes. The message buffer says:

> Done (re)loading bibliography. [2 times]
org-ref-open-bibtex-notes: Org-ref-bib-bibliography-notes is not set to anything

My .emacs setting:
`(setq reftex-default-bibliography '("C:/Users/S/1-TAREAS-NOTAS/biblioteca.bib"))
;; see org-ref for use of these variables
(setq org-ref-bibliography-notes "C:/Users/S/1-TAREAS-NOTAS/3-Biblioteca-copia.org"
      org-ref-default-bibliography '("C:/Users/S/1-TAREAS-NOTAS/biblioteca.bib")
      org-ref-pdf-directory "C:/Users/S/1-TAREAS-NOTAS")
 ;; You may want to set some convenient keys for working in your bibtex file. These commands operate on the citation key at point.
 ;; If you use helm-bibtex as the citation key completion method you should set these variables too.
(setq bibtex-completion-bibliography "C:/Users/S/1-TAREAS-NOTAS/biblioteca.bib"
      bibtex-completion-library-path "C:/Users/S/1-TAREAS-NOTAS"
      bibtex-completion-notes-path "C:/Users/S/1-TAREAS-NOTAS")
 ;; The default key binding to insert a citation is C-c ]. I chose that because I do not like pressing shift to get ). However, this key binding usurps an org-mode agenda file command. To change this, set this variable
;; (global-set-key (kbd "C-c )") 'org-ref-insert-cite-key)
(require 'org-ref)`
