### ISSUE TITLE
got bibliography link [840 times]

### ISSUE THREAD

**Issue by sebhahn** [jkitchin/org-ref#509]
My *Messages* buffer keeps saying "got bibliography link [x times]" which slows writing down in my .org file. Not sure if this is related to org-ref or e.g. helm-bibtex?

**Comment by jkitchin** [comment]
That is an annoying message I have been meaning to remove. I just pushed the removal.

**Comment by sebhahn** [comment]
Ok, I noticed that it if I use `M-TAB` to reorganize the text with real line breaks the message "got bibliography link" doesn't show high numbers any more and doesn't slow down my keystrokes any more.

Does it mean removing this message allows to write "long lines" (i.e. not using `M-TAB`) or is the parsing/checking of citations still going on in the background (because I think this makes it slow if I keep writing in the same long line without making a line break)?

**Comment by jkitchin** [comment]
There is still parsing/checking in the background. That behavior has to do with font-lock, which happens when you edit a line. You may get better performance by setting org-ref-show-broken-links to nil, but then you will not see bad cite links in red.

I am not sure what M-tab is doing for you, for me that is default bound to completion, not reorganizing text.

**Comment by sebhahn** [comment]
Sorry, I meant `M-q`, which runs the command org-fill-paragraph

Performance is much better by setting `org-ref-show-broken-links` to `nil`. Thanks!
