### ISSUE TITLE
Documentation request: workflow to create or jump to a note for a paper

### ISSUE THREAD

**Issue by brabalan** [jkitchin/org-ref#51]
I think this is related to issue #48 but I could not find a solution there.

What workflow do you recommend to create an org-ref note, or jump to such note, for a given paper. Right now I open a scratch buffer, insert the citation link using helm-bibtex, then use the link to go to the note. Is there a way to avoid creating the link?

**Comment by jkitchin** [comment]
If you set these:

;; *** helm-bibtex

(setq helm-bibtex-bibliography "~/Dropbox/bibliography/references.bib")
(setq helm-bibtex-library-path "~/Dropbox/bibliography/bibtex-pdfs")

(setq helm-bibtex-pdf-open-function
(lambda (fpath)
(start-process "open" "open" "open" fpath)))

(setq helm-bibtex-notes-path "~/Dropbox/bibliography/helm-bibtex-notes")

then, you should be able to run 
M-x helm-bibtex

select the entry you want,

press f8 (or press tab/C-z depending on your settings to see additional actions, and select edit notes).

and the note file for that entry will open up.

That works for me. ymmv ;)

**Comment by brabalan** [comment]
I have these:
``` emacs-lisp
(setq org-ref-bibliography-notes "~/Documents/Org/runx-bibliography.org")
(setq helm-bibtex-notes-path "~/Documents/Org/runx-bibliography.org")
```

and when I try to access the notes I get an empty file in the directory `runx-bibliography.org`, instead of going to the entry in the *file* `runx-bibliography.org` (which is where all my notes created with org-ref are). I also get a message `File not found and directory write-protected` which I guess comes from trying to access a file as a directory.

Am I doing something wrong? Are you able to access your org-ref notes (stored in a file, not in a directory) using helm-bibtex?

**Comment by jkitchin** [comment]
hmm.. when I click on a cite link and select 3. Open notes, it does open
a big notes file at the note for that entry. This is different than what
helm-bibtex does with "Edit notes", which does open an empty file
(assuming you did not have previous notes already). I don't use either
one actually, it turns out!

You can try M-x org-ref-open-notes-at-point

with point on  a cite link. that should do what you want.

You could also see here:
https://github.com/jkitchin/org-ref/blob/master/org-ref.el#L3487

where you can see how you might add your own custom note opening
function.

See also
https://github.com/jkitchin/org-ref/blob/master/org-ref.el#L3202 where
you can see how to add a new function to helm-bibtex that might run your
notes function.

**Comment by brabalan** [comment]
Thanks for the suggestions. I’ve been able to extend helm-bibtex as follows
``` emacs-lisp
(helm-add-action-to-source
 "Edit org-ref notes"
 'org-ref-open-notes-at-point
 helm-source-bibtex)
```
using the small patch in pull request #52.
