### ISSUE TITLE
requiring org-ref is slow

### ISSUE THREAD

**Issue by nico202** [jkitchin/org-ref#552]
Hi, thanks for this wonderful package. However since I started using it, my emacs load time is increased a lot. Running this:
```elisp
(require 'benchmark)
(benchmark-run
    (require 'org-ref))
```
shows it requires  6 seconds to load it. Any help on debugging why?
Thanks, Nicolò

**Comment by jkitchin** [comment]
This must be coming mostly from pdf-tools I guess, as that is the longest thing in the scimax startup. pdf-tools is required in org-ref. I don't know why it takes so long, or how easy it would be to make optional.

**Comment by nico202** [comment]
(require 'benchmark)
(require 'pdf-tools)
(benchmark-run
    (require 'org-ref))

This is still 3.4 seconds..

**Comment by nico202** [comment]
Requiring mustache before
```elisp
(require 'mustache)
```
still leads to slow load time (3sec) during which it just prints "Created XXX link."

**Comment by A6GibKm** [comment]
I am using this with ivy and it is still loading helm, which is undesirable. 

Moreover, I haven't found a way of delay org-ref load and at the same time have it loaded when opening a org file.

**Comment by A6GibKm** [comment]
I am also not using pdf-tools so it should not be loaded by default.

**Comment by jkitchin** [comment]
There are still helm functions that have not been rewritten in ivy (notably org-ref) which is why helm still gets loaded. I don't think ivy really supports the features that function uses in helm, so it isn't obvious it can be replaced easily.

At the moment, pdf-tools is tangled with org-ref-pdf, which is loaded to get a variable for pdftotext-executable in org-ref-utils. I am not sure how to delay loading pdf-tools until it is needed. PRs welcome on that.

**Comment by A6GibKm** [comment]
The reason I use ivy is because it is simpler than helm. Having an org-ref-ivy with only the essentials would go on that same direction.

**Comment by jkitchin** [comment]
I also use ivy for that reason, but as I mentioned above, ivy cannot do some things that helm does, so a command like `org-ref` can't be easily converted into an ivy command. Maybe the solution is to make it do something else all together, but for now it is stuck in helm.
