### ISSUE TITLE
org-ref-helm-bibtex.el changes the behaviour of helm-bibtex

### ISSUE THREAD

**Issue by shitikanth** [jkitchin/org-ref#588]
In particular, looking at

```elisp
(cl-loop for i from 0 to (length org-ref-bibtex-completion-actions)
	 for ccell in org-ref-bibtex-completion-actions
	 do
	 (helm-delete-action-from-source (car ccell) helm-source-bibtex)
	 (helm-add-action-to-source
	  (car ccell)
	  (cdr ccell)
	  helm-source-bibtex))
```

This is undesirable because this changes the default action of `helm-bibtex` from opening the associated pdf or url to inserting a citation. 

Ideally, org-ref should create its own helm function, say, `org-ref-helm-bibtex` instead of changing the behavior of `helm-bibtex`. At the very least, this is something that should be configurable.

**Comment by jkitchin** [comment]
There are several solutions to resolve this for you.

1. Configure the variable org-ref-bibtex-completion-actions to have the actions in the order you want them.
2. Don't use the helm-bibtex backend. You can use another helm backend (eg org-ref-helm-cite), or the ivy backend. Then helm-bibtex won't be changed.

**Comment by shitikanth** [comment]
>Configure the variable org-ref-bibtex-completion-actions to have the actions in the order you want them.

That would also affect org-ref-helm-insert-cite-link, which is also undesirable. 

I think are clearly two use cases here - one where the default action should be inserting a link and another where the default action should be opening the pdf or url associated with the citation.

As far as I can tell, the only reason org-ref-helm-bibtex.el is changing the behaviour of `helm-bibtex` is to be able to use helm-bibtex for org-ref-helm-insert-cite-link. This can be just as easily achieved by creating a different helm function rather than changing helm-bibtex itself. Is there any good reason not to do that?

**Comment by jagrg** [comment]
Another problem is that users end up reporting issues (like [this one](https://github.com/tmalsburg/helm-bibtex/issues/250)) to helm-bibtex when the problem is actually in the org-ref code.

**Comment by jkitchin** [comment]
I would be happy to take a pull request for this. 

The main reason it is this way is indeed to get insert citation as the default action. Certainly some other helm function could be written to do that, and probably it could have all the actions of helm-bibtex added to it. I guess as long as it looks and acts like helm-bibtex, it would be fine. I don't use the helm-bibtex backend anymore, but it is the default and I guess that many do, and the default to insert should be preserved for them.

**Comment by jagrg** [comment]
If I understand correctly, org-ref changes the list of actions, and a few variables, namely `bibtex-completion-additional-search-fields`, `bibtex-completion-additional-search-fields`, and `bibtex-completion-format-citation-functions`. I don't think these variables cause any harm though.

One solution then would be to add a hook that runs before helm-bibtex and checks the value of some variable. If the value of the variable changes, org-ref proceeds with the modification. The function would have to compare the current value of the action list[1] against whatever the user intends to use, so that if both lists are equal, the hook does nothing (cc: @tmalsburg).

[1] `(cdr (nth 4 helm-source-bibtex))`

**Comment by jkitchin** [comment]
What if it was possible to just let-bind helm-source-bibtex when called from org-ref? that way helm-bibtex would not be modified, and org-ref would stay the same.

**Comment by jagrg** [comment]
But what if I want to use org-ref-bibtex-completion-actions from helm-bibtex? @shitikanth thinks we should leave helm-bibtex intact and create a separate org-ref-helm-bibtex command. I disagree. I think we need a variable that allows toggling between helm-bibtex vanilla and org-ref's version. It could start with vanilla helm-bibtex by default. This would prevent org-ref from changing helm-bibtex without the user's consent, but still give them the option to choose.

**Comment by jkitchin** [comment]
I also am not that interested in creating a separate org-ref-helm-bibtex command; all it has been is a different order of actions, and some new actions. 

It sounds like there are 3 possibilities:

1. Let org-ref reorder and add new actions to helm-bibtex permanently. This is what is currently done.
2. Do not modify helm-bibtex at all, and leave further customization to the user.
3. Modify helm-bibtex actions in some contexts, but not others.

A new variable, org-ref-helm-bibtex-action-preference,  could indicate which mode the user prefers, e.g.  'org-ref, 'vanilla or 'mixed, which would correspond to items 1, 2 and 3 above. I would probably suggest 'mixed be the default, so that helm-bibtex would appear unaltered when called as helm-bibtex, but would act the way it has from the beginning when called from org-ref.

does that sound like it would resolve the issues?

**Comment by jagrg** [comment]
When you say "when called from org-ref" are you referring to the action list that pops up when we click on a citation link? If that's the case then yes, option 3 (mixed) is fine. That part belongs to org-ref anyway.

**Comment by shitikanth** [comment]
@jkitchin That sounds perfectly reasonable and should cover a variety of use cases.

**Comment by jkitchin** [comment]
@jagrg "when called from org-ref" to me means then you type C-c ] to insert a citation, which calls helm-bibtex from org-ref, and in this case it should have the org-ref actions, including insert citation as the default action.

I don't think this would have any effect on the action list that pops up when you click on a citation link. That shouldn't be invoking helm-bibtex. It might invoke some other org-ref-helm command, but that is independent of helm-bibtex if I recall correctly.

**Comment by jagrg** [comment]
I see. In that case we'd have two helm-bibtex sessions using different actions. Each would start with a different command so hopefully people won't find this too confusing.

**Comment by jkitchin** [comment]
I have tried to make an implementation of this. Now, you should be able to get the following behavior with these in your init file:

Nothing, or `(setq org-ref-helm-bibtex-action-preference 'org-ref)` will be the same as before.

`(setq org-ref-helm-bibtex-action-preference 'vanilla)` will not modify the helm-bibtex actions at all.

`(setq org-ref-helm-bibtex-action-preference 'mixed)` should only modify the actions when you use it through org-ref, e.g. C-c ], and not modify them when you call it via M-x helm-bibtex.

This is not in the master branch yet. I am not a helm-bibtex user, so if someone who is could test it and let me know it works ok for them I would appreciate it. Then I can merge it in.

**Comment by jkitchin** [comment]
@tmalsburg I don't think there need to be any changes to helm-bibtex. It works fine. The issue is mostly about user preferences for action order, and I think this makes it possible for users to get what they want.

**Comment by 9309** [comment]
For the mixed preference, I needed to add  `copy-tree` in the let binding for helm-source-bibtex inside `org-ref-helm-insert-cite-link` to get it to work (otherwise the modified actions would persist).
```
(let ((bibtex-completion-bibliography (org-ref-find-bibliography))
          (helm-source-bibtex (copy-tree helm-source-bibtex)))
      (when (eq 'mixed org-ref-helm-bibtex-action-preference)
```
Afterwards, the mixed preference works perfectly.
