### ISSUE TITLE
Cannot add Bibtex-Entries from DOI

### ISSUE THREAD

**Issue by Meister-Asrael** [jkitchin/org-ref#590]
Dear John,

using version 20180706.614, I am unable to use the function "doi-utils-add-bibtex-entry-from-doi". I get the error message "JSON readtable error". It seems to be a parsing error in the json.el.gz, corrosponding to a newline character at first position in the string.

I tried doi.org/10.1007/3-540-44750-4_35 for example.

best regards

**Comment by jkitchin** [comment]
I don't get that error. You should use this for the doi: 10.1007/3-540-44750-4_35

However, you will get another error, because this doi returns a chapter bibtex entry which is not currently supported by org-ref. The bibtex file will have the raw json dumped in it. I will leave this open until I can get that fixed.

**Comment by jkitchin** [comment]
I think 4818977 will address problem 1 reported by @fpopineau. This happens when you search for a bad doi. 

The second issue sounds related to drag and drop, which is hard to fix and not high on my priority list right now.

**Comment by fpopineau** [comment]
Hi John,

Thanks for the commit addressing the first point. 
To me, the second issue seems more related to `org-ref-pdf-doi-regex` which
makes the colon after doi optional. I have pdf-greped for "doi" in a bunch of pdf files
and the strings returned are a nightmare in their variability.
But definitely "doing" should be forbidden IMHO.

**Comment by jkitchin** [comment]
I modified the regexp a little to make it more restrictive. I don't think this feature is a very good one, precisely because of the variability you refer to. It seems it will take an extraordinary effort to make this work, especially compared to how simple it is to copy and paste a doi with other org-ref commands.
