### ISSUE TITLE
Not all functions are working (notes, files, BibLATEX-fields)

### ISSUE THREAD

**Issue by hdevriese** [jkitchin/org-ref#615]
tmalsburg from Helm-BibTeX advised me to post the following in the org-ref project:

Hello,

I have been trying to work with Helm-BibTeX and Org-Ref. I installed through Melpa-stable on gnu Emacs 26.1, system: OSX 10.14.1. Helm-BibTeX 2.0.0, org-ref 1.1.1.

When adding keywords through Helm-BibTeX, I get this message:
wrong type argument: strings, ("Bibtexkey for selected entry")

When trying to add a note through Helm-BibTeX, I get this message:
symbol's function definition is void: Helm-BibTeX-edit-notes
Similar messages for inserting pdf etc.

I tried to see if BibLATEX fields are recognized, which isn't the cas, for instance for the "file" field.

I can access my .bib file through Helm-BibTeX though and some fonctions work as expected: Insert BibTeX key/entry/formatted citation works. Using Cite:bibtexkey in org-files works.

Any thoughts ?

I don't know anything about programming, I might be doing something very obviously wrong.
Copy of .emacs in attachment.

Kind regards,
HDV

[copyinitfile.txt](https://github.com/jkitchin/org-ref/files/2568433/copyinitfile.txt)

**Comment by jkitchin** [comment]
To get biblatex fields to be recognized you probably have to tell emacs what bibtex dialect to use, e.g. in an init file add:


`(setq bibtex-dialect 'biblatex)`

Could you be more specific how you are getting the errors, e.g. a step by step description:

M-x helm-bibtex
tab
name of action...

I assume you have copied and pasted some error messages, but they are confusing to me. For example, the literal string Helm-BibTeX-edit-notes does not exist in the org-ref code base. Maybe it is a really old version, since you are using something from MELPA stable.

**Comment by hdevriese** [comment]
Installing from MELPA instead of MELPA stable fixed the issue. I didn't check out everything yet, but things that wouldn't function, work fine now. Thank you.
