### ISSUE TITLE
Automatically download PDFs or use cite:link click to download

### ISSUE THREAD

**Issue by moritzschaefer** [jkitchin/org-ref#622]
While drag n drop works fine (and copies the PDF into the defined folder), using doi-utils-add-bibtex-entry-from-doi finds the PDF but only opens it in the browser instead of downloading it into the defined folder ( org-ref-pdf-directory). 

Is this the desired behaviour (as it seems unintuitive to me) and can it be changed (I did not find anything in the manual).
Furthermore it is stated that a click on a cite:link opens a menu with options (including the option to download the PDF). For me it opens a HELM buffer with the label "Choose" but without any option to choose from. 

I did not find any error message in *Messages*. I am using spacemacs and configured org-ref as described in the README

**Comment by jkitchin** [comment]
What you describe happens when there is no recipe to find the pdf. Some publishers make it difficult to download pdfs. Without some specific doi to figure out if it is one of those publishers, I am not sure what else I can say.

You should be able to click on a link and get a menu. If you don't see a helm menu, then something has not been configured fully I guess. Can you run helm-bibtex?

**Comment by moritzschaefer** [comment]
Thank for the quick response!

For the first part of the issue: I'm talking about the case where a PDF CAN be found. In that case it is opened in the browser automatically (and I could save it to my hard drive with Ctrl+S), however it is not automatically being saved to the papers folder (which should be easy as the PDF is being found and opened in the browser). Here is a DOI where I observe this effect: 10.1016/j.jgg.2017.01.005

For the second part: helm-bibtex works great and shows a list of all my references along with additional "Fallback options".

**Comment by jkitchin** [comment]
I think that is an example of a pdf that is not easy to download because it is hidden behind some layers of javascript or redirect, etc. If you try to wget the pdf url you get an html page, not the pdf. So, even though it is easy to save it with some mouse clicks, it is not easy to automate the download. 

I have confirmed the second issue. I am not sure why it is happening yet though.

**Comment by moritzschaefer** [comment]
Thanks for the fix. Indeed it does work for entries WITH a PDF. I'll wait until it made its way into MELPA as I am not sure on how to overwrite my currently installed version with the github one.
