### ISSUE TITLE
Suggestion : support Zotero as a fallback source.

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [jkitchin/org-ref#652]
The [Zotero](https://www.zotero.org/) bibliography manager has become very popular in some scientific domains (and in medicine), not least because of a unique feature: the ability to extract bibliographic information from some Web pages (notably Pubmed, most publishers' repositories and Google Scholar). This feature is quite precious for "quick looks" at an unknown subject as well as for "packrat types", who seek to collect exhaustive information about a subject before publishing (or internally report).

In consequence, many researchers have built some respectable databases (my own repository, broken up in four collections, whared with different people, is about 14 000 references, de-duplicated, and is quite usable). Most people use it with a Word plugin allowing dynamic queries to onsert a reference "in the right place" and maintaining the reference list. Using Zotero for a new LaTeX/org document usually implies some form,of export to Bibtex, which can be automatically refreshed thanks to another [Zotero plugin](https://github.com/retorquere/zotero-better-bibtex).

A primitive connection between Zotero and emacs exist, implemented in a [Zotero extension](https://github.com/egh/zotxt) and an [emacs ELPA package](https://github.com/egh/zotxt-emacs). My attempts at using it showed that:
- it works, but
-  it is probably too primitive to be usable in "real-world" academic writing ;

however, these modules open the possibility to dynamically query a not inconsiderable bibliographic database.

Would you consider a module offering a local Zotero database as a fallback to `org-ref` ?

**Comment by jkitchin** [comment]
This isn't something I am interested in working on; I don't use Zotero, so I wouldn't be able to support it very well. org-ref duplicates some of the functionality you describe already, certainly less well than Zotero does, but that is largely because I haven't found it crucially useful in my own work.

org-ref is build around bibtex, primarily for the use-case of exporting to latex. You could use any other backend database, as long as there is some way to get a list of candidate entries to choose from, and then a way to insert a unique key that maps to one of those entries. After that, you need to be able to export the org-ref links to some format that can be converted to the desired document format. I don't know how you would do that with Zotero that wouldn't involve exporting it to bibtex, and I don't know how you would use an org-ref link to get a citation in a docx file. 

You would have to redefine (or turn off) some features of how the links get fontified, e.g. cite links turn red when the keys are not in a bibtex file, and this would have to be modified to check zotero, or turn off the feature.

All that said, if someone wrote an interface like this, and wanted to have it in org-ref, I would probably accept it, and could even advise on how to connect things into it/modify org-ref to make that easier. It isn't a project I would take on myself though.
