### ISSUE TITLE
Notes of a page of a book and how to link them

### ISSUE THREAD

**Issue by Ypot** [jkitchin/org-ref#696]
Hi

Is there a way to make a note related  to a chapter or a page of a book? 

And if I wanted to make a link to a note, what would be your recommendation? 

Thanks for this great package.

**Comment by jkitchin** [comment]
you should be able to make a note to any bibtex entry. There is a chapter bibtex type, so you can make an entry for the chapter, and then make a note to it. 

For a link to a note, I am not sure what you mean. You can make a regular org link to it, since the note is probably an org file, or a heading in one. Is that what you mean? If you mean a cite link with a reference to a page number, you can do it like this:

[[cite:Dominik201408][See page 20::, for example]].

**Comment by Ypot** [comment]
This reference 
[[cite:Dominik201408][See page 20::, for example]]
 I thought it was done using "pre/post text" feature. But I understand that it is a type of cites. How can I use that chapter bibtex type? 
Then if I clicked on it to make a note, I suppose it would be created a new subheading like this?:

** TODO Carsten Dominik - The Org Mode 8 Reference Manual - Organize your life with GNU Emacs (2014)
...

*** See page 20::, for example
...
CUSTOM_ID: Dominik201408-See page 20::, for example
...

Something like that?

**Comment by jkitchin** [comment]
You may be mixing up cite types and bibtex types. In this example, Dominik201408 is the key to a bibtex entry, which can be any kind of bibtex type, e.g. a chapter looks like this (with the fields filled in for example.

```
@InBook{Dominik201408,
  ALTauthor = 	 {},
  ALTeditor = 	 {},
  title = 	 {},
  chapter = 	 {},
  publisher = 	 {},
  year = 	 {},
  OPTkey = 	 {},
  OPTvolume = 	 {},
  OPTnumber = 	 {},
  OPTseries = 	 {},
  OPTtype = 	 {},
  OPTaddress = 	 {},
  OPTedition = 	 {},
  OPTmonth = 	 {},
  OPTpages = 	 {},
  OPTnote = 	 {},
  OPTannote = 	 {}
}

```


I don't use notes, but I would expect that this would make a notes entry based only on the key Dominik201408. You would have to write the notes about a particular page. There is not a way to jump right to that note by default though. you might be able to write your own function that would do that. See the variable `org-ref-open-notes-function`.
