### ISSUE TITLE
Any way to speed up `org-ref-helm-insert-cite-link`?

### ISSUE THREAD

**Issue by dangom** [jkitchin/org-ref#767]
I have a global library.bib file with some thousand entries. It always takes `org-ref-helm-insert-cite-link` a couple of seconds to parse the file, and as more entries get added to it, the parsing and sorting get slower (as ofc would be expected). I was thus wondering if there is any way to compensate for the inevitable slowdown?
Perhaps I could pay the parsing price upfront, possibly during the loading of org-ref, or have the parsed results cached somewhere? Or even delegating the parsing and sorting to some other cli tool?

The reason I like to have a file with all of my entries is mostly for extra serendipity. Sometimes searching for an article will show me related articles, and remind me of something I wouldn't have thought of otherwise.

Any tips are welcome!

**Comment by jkitchin** [comment]
I would try switching to a different backend. I wrote the  `org-ref-helm-cite` and 	`org-ref-ivy-cite` backends because of the reason you mention. These use a cache mechanism which is fast for me. They should automatically reparse the bib files when you add new entries, so it is slow if you do that a lot while writing, but if you add them all at once, then it just reparses once the next time you try citing.

I am not aware of a cache mechanism for helm-bibtex that would offer a similar speed up.

**Comment by dangom** [comment]
Thanks for the quick reply. There is indeed a speed-up when using `org-ref-helm-cite` - I wish I'd been aware of `org-ref-completion-library` earlier!
