### ISSUE TITLE
Symbol’s function definition is void: org-ref-possible-bibfiles

### ISSUE THREAD

**Issue by jthaman** [jkitchin/org-ref#777]
I receive the error `doi-utils-add-bibtex-entry-from-doi: Symbol’s function definition is void: org-ref-possible-bibfiles` when trying to add references to my bib file. This just started happening a few days ago.

Here is the configuration that I use:

```
(use-package org-ref
  :defer t
  :ensure t
  :custom
  (org-ref-open-pdf-function 'xah-open-in-external-app)
  (doi-utils-open-pdf-after-download t)
  (org-ref-show-broken-links nil)
  (bibtex-autokey-year-length 4)
  (bibtex-autokey-name-year-separator "-")
  (bibtex-autokey-year-title-separator "-")
  (bibtex-autokey-titleword-separator "-")
  (bibtex-autokey-titlewords 2)
  (bibtex-autokey-titlewords-stretch 1)
  (bibtex-autokey-titleword-length 5)
  (org-ref-bibliography-notes "~/references/notes/notes.org")
  (org-ref-default-bibliography '("~/references/references.bib"))
  (org-ref-pdf-directory "~/references/docs/"))
```

Thank you for authoring and maintaining this wonderful package.

-John

**Comment by jkitchin** [comment]
That function is defined in org-ref-core.el. I guess you must be having some other error before this that maybe leads to org-ref not fully loading?

**Comment by jthaman** [comment]
Ah, thanks. The error came from deferring the package. I call `doi-utils` functions through a hydra which does not load org-ref. Removing `:defer t`  or settings `:defer 5` fixes it.

**Comment by averter** [comment]
Hi both,
I am having the same issue for a different reason. Whenever I try to install org-ref there are several errors because it cannot find queue
`org-ref.el:40:1:Error: Loading file /home/averter/.emacs.d/elpa/queue-0.2/queue.elc failed to provide feature ‘queue’`
and as a consequence most functions in `org-ref-core.el` are not installed. However, when I check the list of emacs packages queue is definitely installed... Another side effect of the installation are these two not registering prefix warnings [discussed here](https://github.com/jkitchin/org-ref/issues/822#issuecomment-759540263). Do you have any other suggestions? Thanks

**Comment by jkitchin** [comment]
this probably means the queue package at /home/averter/.emacs.d/elpa/queue-0.2/ is corrupted. Try deleting that directory.
