### ISSUE TITLE
Brackets in names when exporting to HTML

### ISSUE THREAD

**Issue by liebkne** [jkitchin/org-ref#806]
I'm using the setup like

```
bibliographystyle:author-year
bibliography:../bibliography/references.bib
```

and get citations in HTML like

```
{Cho} 2014; {Sutskever} 2014; {Neubig} 2017; {Luong} 2015; {Dai} 2015; {Wiseman} 2016
```

How can I remove these brackets? They are originally included in the `bibtex`...

```
@ARTICLE{sutskever-2014-seq2seq,
  adsnote      = "Provided by the SAO/NASA Astrophysics Data System",
  adsurl       = "http://adsabs.harvard.edu/abs/2014arXiv1409.3215S",
  archivePrefix= "arXiv",
  author       = "{Sutskever}, I. and {Vinyals}, O. and {Le}, Q.~V.",
  eprint       = "1409.3215",
  journal      = "ArXiv e-prints",
  keywords     = "Computer Science - Computation and Language, Computer Science
  - Learning",
  month        = sep,
  primaryClass = "cs.CL",
  title        = "{Sequence To Sequence Learning With Neural Networks}",
  year         = 2014
}
```

Thanks!

**Comment by jkitchin** [comment]
I guess you could put an advice around `org-ref-format-cite` that would remove the curly brackets.  This will only solve it for cite types, if you use other types like citep, you would need to advise the corresponding format functions. See `org-ref-clean-unused-entry-html` for some hints on how to modify the output.

The other place you could have an issue though is in the bibliography, if that is ok, it is because the entries are already cleaned up, just not the keys.

Let me know how that works out, and we can see if there is a more permanent solution perhaphs.
