### ISSUE TITLE
void function dnd-unescape-uri

### ISSUE THREAD

**Issue by gdindi** [jkitchin/org-ref#812]
Version: 20201013.1427
Commit: 2a91b6f67dc3116b0b688c1242ce67d90d833326

org-ref-pdf-to-bibtex calls which seems to be void. 

I need to do this to make the function work:
(defalias 'dnd-unescape-uri 'dnd--unescape-uri)

**Comment by jkitchin** [comment]
I do not understand this issue. Are you saying `dnd-unescape-uri` is not a function for you, and `dnd--unescape-uri` is? Is that why the alias solves your problem? For me the first one is defined in dnd.el, and the second is non-existant.

**Comment by gdindi** [comment]
I am sorry. My sentence was incomplete. `dnd-unescape-uri` is void for me (I am on emacs master). The fuction seems to have been renamed with a double dash.

**Comment by jkitchin** [comment]
Ok. Thanks for the report. I have added a conditional defalias that I think will solve this.

**Comment by yangsheng6810** [comment]
It may not be a good idea to warn if neither `dnd-unescape-uri` nor `dnd--unescape-uri` exists. They are not autoload functions. So unless `dnd` is loaded, you will always produce a warning, which can be both annoying and unhelpful.

**Comment by jkitchin** [comment]
Indeed, I have already gotten an email about that. I have just pushed something that comments those out for now.

**Comment by paulapatience** [comment]
@yangsheng6810: What I don't understand is that none of the other dnd functions called by org-ref are autoloaded. Only dnd-protocol-alist is, and dnd-unescape-uri is called before that anyway.

Probably the reason @jkitchin received an email about the warning is because the current defalias would never take effect because dnd--unescape-uri is misspelled as dnd--escape-uri in [org-ref-pdf.el](https://github.com/jkitchin/org-ref/blob/8aa2bb45268f660956151547533689d4ec30378d/org-ref-pdf.el#L46) and [org-ref-url-utils.el](https://github.com/jkitchin/org-ref/blob/8aa2bb45268f660956151547533689d4ec30378d/org-ref-url-utils.el#L62). Correcting the typo should fix everything. In particular, I don't encounter the problem mentioned by @yangsheng6810 after correcting it.

**Comment by paulapatience** [comment]
Ah, and in fact, the defalias in org-ref-url-utils is unnecessary (and unconditionally skipped, resulting in the warning being displayed), since that file requires doi-utils, which requires org-ref-utils, which requires org-ref-pdf, so dnd-unescape-uri is already defaliased and thus fboundp'd.
