### ISSUE TITLE
[Feature Request] Use org instead of bibtex

### ISSUE THREAD

**Issue by JonathanReeve** [jkitchin/org-ref#837]
When opening a note for a source, using org-ref-open-bibtex-notes, I can populate a note with all the necessary bibliographic information, so that the PROPERTIES drawer contains the title, author, journal issue number, and so on. This means that effectively, I'm  maintaining two separate copies of this bibliographic information: once in the bibtex file, and again in the org file. Why not just cut out the middleman here, and go all-in with Org? If there were a way to store all bibliographic information in Org, rather than in bibtex, then I wouldn't have to keep switching between my notes file(s) and my bib file. 

Then, all that would be necessary is to get the citeproc to read from the metadata in org files, rather than the bibtex files.

**Comment by jkitchin** [comment]
That is possible, and if you only ever use org, and citeproc that would make sense. org-ref started out mostly for using org to generate LaTeX files though for scientific publications. For that, you need the bibtex files, and with doi-utils it is easy to download bibtex entries.

I don't see it as very practical to try to support both kinds of backends, there is so much reliance on bibtex already.

**Comment by yantar92** [comment]
> If there were a way to store all bibliographic information in Org,
> rather than in bibtex, then I wouldn't have to keep switching between
> my notes file(s) and my bib file.

I am in process of implementing something similar to what you want:
https://github.com/yantar92/org-capture-ref. The idea is using org
entries as a source of bibtex.

**Comment by jkitchin** [comment]
Isn't this what org-bibtex is for?

**Comment by yantar92** [comment]
> Isn't this what org-bibtex is for? 

Hmm. I knew about ox-bibtex, but not about org-bibtex (which lives in
ol-bibtex.el, strangely). I guess it should not be too hard to implement
the requested feature:

1. org-ref could generate .bib file by exporting all the headlines with
paper metadata during org->manuscript export.

2. org-ref could insert headlines directly with org-bibtex-yank instead
of populating the .bib file.

3. org-ref could use helm-org-ql instead of helm-bibtex to search across
references.

The paper pdfs may even be stored and attachments to their headings.
That way, supplementary information can also be stored as attachment
alongside the main paper text.

As for org-capture-ref, I also wanted some way to generate bibtex
entries for any reference, even without DOI. For example, some new
papers are published online before their DOI is registered in doi.org.
org-capture-ref can parse the web page for paper metadata and even
generate bibtex for web pages without DOI (like blog articles, or
books).

**Comment by jkitchin** [comment]
You can see more about org-bibtex here: http://gewhere.github.io/org-bibtex

On 3, you do not have to use helm-bibtex, that is for a specific org-ref backend. You can also use ivy or reftex. In any case, it is a massive rewrite to use org as a database instead of bibtex for org-ref. My experience in trying to use org as a database has been that it is not practical to search large org databases frequently. It is just too slow. Even in org-ref, I found searching bibtex files with helm-bibtex too slow, and wrote a cache system to use with ivy. I also wrote a cache system to use for contacts stored in org-files, because it is just too slow to search them when you have a lot of them.

You might check the functions in org-ref-url-utils, especially `org-ref-url-html-to-bibtex`.

**Comment by yantar92** [comment]
> You can see more about org-bibtex here: http://gewhere.github.io/org-bibtex

Thanks. I have seen that link. org-bibtex.el is not present anymore in
latest org. The functions appear to be moved to ol-bibtex.el at some
point.

> On 3, you do not have to use helm-bibtex, that is for a specific
> org-ref backend. You can also use ivy or reftex.

Sorry, I was not clear. I meant to say that org-ref could use search in
org files instead of the bib file (using any backend).

> In any case, it is a massive rewrite to use org as a database instead
> of bibtex for org-ref.

I do not see this rewrite as impossible. Would you be interested in pull
requests?

> My experience in trying to use org as a database has been that it is
> not practical to search large org databases frequently. It is just too
> slow.

With latest org-ql and my performance patch to helm-org-ql [1], I can
search across all my org files (>15000 headings) nearly instantly.

> You might check the functions in org-ref-url-utils, especially `org-ref-url-html-to-bibtex`. 

That was my starting point when I decided to write org-capture-ref.
org-ref-url-html-to-bibtex is very too simplistic and fails on many
URLs. A lot more metadata can be collected. For example, sciencedirect
pages (with not yet registered DOI) can be parsed as an @article with
all the necessary fields. Amazon or goodreads book pages can be parsed
for ISBN.

[1] https://github.com/alphapapa/org-ql/pull/162

**Comment by jkitchin** [comment]
I have thought about this alot. If you did want to try making it possible for org-ref to support either bibtex or org as the database of bibliography entries, you should do it on a separate branch. Bibtex is so integrated into org-ref-core that it would be a very substantial job to put an interface layer that you could choose between org and bibtex. I think this interface would mainly affect the cite links, and would affect nearly every part of how to follow links, the help-echo, and the faces, as well as the note functionality (which I have never liked much) and the export functions for backends other than latex. You would also have to modify the selection backends so that they get data from the right places.

In the end, I think org-ref would have to still support bibtex. It is still the standard for latex, which is my main application for org-ref. If it can also support an org-backend that would be pretty nice.

I can see some advantages to an all org database, especially related to notes. I can see some disadvantages too. It sounds promising you can search a lot of headings quickly, although that has not been my experience. I can't currently use helm-org-ql because of https://github.com/alphapapa/org-ql/issues/185, and my experience with org-ql in large projects is that it is not fast enough (I am an amateur with it though). I do have a project I call org-db that indexes org files into a sqlite file, some 2400 files and 35K headings, and it is fast. I use this for managing contacts, searching headings, etc. it would be easy to use this as a source of org bibliography entries if there is a way to clearly identify a heading as a bibliography entry, e.g. by a property, like :CITATION_KEY:. Then, you just need to modify the help-echo function for the links, the follow function for the link, and add new export functions for latex to generate and use a local bibtex file, etc.

**Comment by benthamite** [comment]
I would really appreciate such a feature.

In the meantime, an option is to have the bibliographic information added as a bibtex code block to the org file containing the notes, as described [here](http://www.cachestocaches.com/2020/3/org-mode-annotated-bibliography/). Then one can tangle that file to generate a proper bibtex file org-ref can read.
