### ISSUE TITLE
[Question] Create bib(la)tex entry given path to file?

### ISSUE THREAD

**Issue by apc** [jkitchin/org-ref#874]
First, thanks for this wonderful package. 

Next, apologies if this is something clearly spelled out elsewhere: I've been looking for a while but cannot figure out a solution. 

I'm trying to write a function that will, given a path to a PDF file, and if necessary a doi for the relevant file, do the following: 

-  add a bib entry to `org-ref-default-bibliography`. 
- move the PDF file to `org-ref-pdf-directory`, and 
- rename the PDF using information from the corresponding entry. 
 
(Adding the path to the 'file' field of the bib entry would be nice, but I think I can figure that out with the l little Elisp I know.)

Is there something in `org-ref` that already does this? 

I assume `doi-utils-add-bibtex-entry-from-doi` can accomplish the first thing, so I'm trying to find out what the best way to piggy back on this function to do the last two steps. If there's already a way to do this, though, it'd save me a lot of time (see above: "... the little Elisp I know"). 

Thanks!

**Comment by jkitchin** [comment]
I am not sure there is something that reliably does this. in `org-ref-pdf.el` there is `org-ref-pdf-to-bibtex` which works when you open the pdf in emacs and there is a doi that can be scraped from the pdf.  there is also `org-ref-pdf-dir-to-bibtex`. I don't find either of these 100% reliable though, because it is so difficult to reliably match doi patterns. I end up doing what you describe more manually, which is use `doi-utils-add-bibtex-entry-from-doi` to get the entry. That copies the key to the clipboard so it is a paste operation away to rename the pdf, and then i manually move it.

**Comment by apc** [comment]
Thanks for your quick reply! I wonder if one could make use of `bibtex-completion-add-pdf-to-library` here (which I just discovered!). I'll play around and post a reply here if I come up with something I think others might find helpful. In the meantime, I'll just close this as you more than addressed my question.
