### ISSUE TITLE
drop package requirement for helm and ivy?

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [jkitchin/org-ref#876]
Hello, I use a different completion framework that is not either helm or ivy, although this might a good chance to try out helm, personally I think that it would be better if those packages are not installed as part of the dependencies.

**Comment by jkitchin** [comment]
This is not currently possible, and not likely to be possible in the future. org-ref is not simply a completion tool. In both helm and ivy, it also leverages unique capabilities of each backend to provide more than completion capability, e.g. menus of actions to do a variety of things with a cite/label/ref link. It is not currently possible to separate that from completion. 

Once, I tried to separate out the packages to avoid this, so you could say only install the helm version or ivy version. That did not succeed, however.

At the moment your only path to avoid helm and ivy is to install the source from github, and create your own backend that does what you want.

**Comment by bdarcus** [comment]
I'd like to weigh in on this, if you do get around to rewriting and simplifying org-ref around org-cite.

I'm wondering if it would be possible to have swappable completion systems, with completing-read and at-point as default, but that one could install instead, for example separate `helm-org-ref` and `ivy-org-ref` packages to use them instead?

There's been a ton of activity around these default completion APIs in the past year, and some of that work is now landing in emacs core.

I was actually starting to write a `complete-key-at-point` function for my `bibtex-actions` package (which relies on completing-read-multiple, but wraps `bibtex-completion` functions), but could imagine it being in an `org-ref v2`, depending on how that evolves.

Or maybe I could split out my `bibtex-actions-read` and (when done) the capf such that it could be used in an `org-ref v2`?

Anyway; just thought I'd throw the idea out there.

It seems with this, plus org-cite, plus recent WIP enhancements to parsebib, etc., there could be room to develop smaller, more targeted packages that can still work well together.

https://github.com/joostkremers/parsebib/issues/12

**Comment by jkitchin** [comment]
I guess that there will need to be a total rewrite of org-ref in the future. Part of it would be to take out all the cite parts of it, since presumably this is going to be covered in org-cite. The rest will probably focus on just org-crossref for labels/ref links.  I don't have a timeline for if/when that might happen. First, I need to figure out how to use the new completion tools instead of ivy, it isn't too obvious right now.

**Comment by bdarcus** [comment]
> I guess that there will need to be a total rewrite of org-ref in the future. Part of it would be to take out all the cite parts of it, since presumably this is going to be covered in org-cite. The rest will probably focus on just org-crossref for labels/ref links. 

Makes sense.

> First, I need to figure out how to use the new completion tools instead of ivy, it isn't too obvious right now.

You could always take a look at what I've done with bibtex-actions. This was a learn-elisp-while-doing project for me, but I had help from people with much more expertise, and it's a small code base.

https://github.com/bdarcus/bibtex-actions

Moreover, the test directory includes a script that will setup both selectrum (default) and vertico, so one can kick the tires using Emacs -Q, and compare two different completing-read compatible completion UIs.

**Comment by jkitchin** [comment]
I have tried following bibtex-actions, but I don't see how it works. Is there a simple example like how do you use this: `(completing-read-multiple "choose: " '(a b c))` where you can select multiple entries, and then choose an action to work on them? e.g. RET to display a message, and some key to either insert them at point, or copy to the clipboard?

**Comment by bdarcus** [comment]
> I have tried following bibtex-actions, but I don't see how it works.

If you do `./run.sh` from the test directory, you can do the following to insert a citation key in a buffer.

1. `M-x bibtex-actions-insert-key`
2. browse and select one, hit return

To select multiple, you use tab.

You can also access additional commands/actions from a minibuffer candidate selection by doing `M-o` (which calls `embark-act`).

The bibtex-actions commands are all completing-read-based wrappers around the bibtex-completion functions.

Does that clarify?

**Comment by jkitchin** [comment]
That part was all clear,   There is a lot of action to insert a citation from that. Is there a way to set a default to not prompt for everything?

What is not clear is how to wire it all together. it looks like you are avoiding installing ivy/helm, but adding selectrum, embark, consult, marginalia, which-key,...

**Comment by bdarcus** [comment]
> That part was all clear, There is a lot of action to insert a citation from that. Is there a way to set a default to not prompt for everything?

Yes. There have been some recent discussions about this at embark, but I haven't had time recently to check the upshot of that. 

But per below, embark does have a built-in UI for the actions, which uses completing-read IIRC; which-key as seen in the screenshot is optional.
 
> What is not clear is how to wire it all together. it looks like you are avoiding installing ivy/helm, but adding selectrum, embark, consult, marginalia, which-key,...

Yes, a series of smaller, targeted, packages, with mix-and-match flexibility.

1. selectrum, vertico etc (Emacs 28 adds icomplete-vertical-mode, for example) all provide completing-read compatible browsing and selection, and to run the command on the selections
2. orderless provides a completion-style similar to what one gets in helm or ivy
3. embark and marginalia add annotations and contextual command binding
4. which-key is just one way to display those contextual commands

I don't use consult at all here, but do use it more broadly.

None of the above is required in the package formally (only dependency is bibtex-completion), and using only 1 and 2 go a long way for basic functionality.

3 is nice-to-have (marginalia, for example, adds annotations for all emacs commands, and embark is pretty useful), but not necessary.

4 is also totally optional. I mainly focus on which-key because I'm a doom user (and I guess developer), and doom uses which-key.

**Comment by bdarcus** [comment]
I guess some of this might benefit from being linked to a new issue, but just wanted to update on related issues.

I recently merged this commit, which uses embark at-point support to bind additional actions to `bibtex-actions-at-point` (which wraps `bibtex-completion-at-point`). Will be trivial to then turn this into an `org-cite` "follow" processor.

https://github.com/bdarcus/bibtex-actions/commit/ba8f4e5a5ef394aad5af64b9cadad834fef0b248

It would be really cool if we could figure out a way to mix and match functions from different packages through this sort of mechanism.
