### ISSUE TITLE
Exporting the manual to HTML

### ISSUE THREAD

**Issue by edipretoro** [jkitchin/org-ref#91]
Hi,

I've tried to export the manual (org-ref.org) from the git repository and I get a « user-error: Unable to resolve link "bibliography link" ». 

I've just installed org-ref from melpa and I'm using the last org (Org-mode version 8.3.2 (8.3.2-51-g713fe8-elpaplus @ /Users/manu/.emacs.d/elpa/org-plus-contrib-20151221/)). 

Thanks in advance!

Emmanuel Di Pretoro

**Comment by jkitchin** [comment]
I suspect that is because the bib file isn't part of the melpa package. I will try adding it to the melpa recipe.

**Comment by edipretoro** [comment]
Hi. 

Thanks for your answer. I don't think it's related because I was running the export from a clone of this git repository. And the .bib file was there. 

I've turned debug-on-error but I didnt get more information.

**Comment by jkitchin** [comment]
You are right. Somethings have changed in org. The error you saw is because I had the <<bibliography link>> in a comment, which used to work but doesn't seem to in newer versions of org. I fixed that. You also need to require a few org-ref libraries so the rest of the links resolve. I pushed some directions in org-ref.org on this.

**Comment by edipretoro** [comment]
And that problem is solved. Thanks for your diligence!
