### ISSUE TITLE
Inserted citatation with an extra "&"

### ISSUE THREAD

**Issue by xiangsheng** [jkitchin/org-ref#950]
After upgraded to v3, when I insert a citation into a file, it is formatted as `cite:&abc`. In v2 version, it is formatted as `cite:abc`. I think the v2 version is more proper and don't understand why an extra "&" is inserted in v3.

I search the code and find the extra "&" coming from the following line in the function `org-ref-insert-cite-key`.
```
(if (null (assoc type org-ref-cite-types))
	;; Not on a link, so we just insert a cite
	(insert (format "[[%s:&%s]]"
			(if set-type
			    (completing-read "cite type: " org-ref-cite-types) 
			  org-ref-default-citation-link)
			key))
```

Is it possible to add an option to deciding whether this "&" is inserted or not? Otherwise, I have to override this function locally.

**Comment by jkitchin** [comment]
The & is intentional, to differentiate v3 cites from v2 cites. v3 supports a broader range of syntax than v2. It exports correctly, and removes the &.

In principle, you can control this with `(setq org-ref-cite-insert-version 2)`. I just pushed some fixes for this though, so you will need to update org-ref for that to work.

**Comment by xiangsheng** [comment]
OK, thank you.
