### ISSUE TITLE
error "crefrange links are not supported yet" although no cref link used

### ISSUE THREAD

**Issue by alejandrogallo** [jkitchin/org-ref#952]
I'm getting this error although no crefrange link is being used.

I am building this documentation

  https://github.com/cc4s/user-manual/runs/4430682303?check_suite_focus=true#step:4:706

And I am using the latest org-ref from melpa

  https://github.com/cc4s/user-manual/runs/4430682303?check_suite_focus=true#step:4:567

I have a couple of `cite:` links to show my coworkers how to cite,
but it does not seem to work right now.

Do you have an easy fix or should I take a look at it?
I guess somehow at the time of publishing it thinks that there are some cref links
that are actually not there.

This is the configuration I am using

```lisp
(use-package org-ref
    :defer t
    :ensure t
    :config
    (setq bibtex-completion-bibliography
          (list (expand-file-name "./group.bib")))
    (cc4s-log "Bib files: %s" bibtex-completion-bibliography))
```

**Comment by jkitchin** [comment]
hm. that happens in org-ref-refproc-replacement, which is related to a ref link, not a cite link. That error comes from a fall-through case where org-ref at least thinks there is a crefrange link.

It looks like you are trying to publish the org-ref.org document maybe? (https://github.com/cc4s/user-manual/runs/4430682303?check_suite_focus=true#step:4:692)  Is that intentional? If so, that is probably where the error comes from since that describes those links. I guess you could avoid that by adding some ignore patterns to your project.

**Comment by alejandrogallo** [comment]
I feel very stupid, I am sorry I wasted your time. That is exactly it, I have the `emacs-user-directory` set to the local `.emacs` directory for the makefile and now the org files inside that directory are also being considered, so I just have to exclude.

Thank you very much, we are going to use org-ref quite heavily around here ;)
Cheers!
